### ISSUE TITLE
Reminders not working

### ISSUE THREAD

**Issue by CrazyWolf13** [greaterthanlessthan/vikunja-to-ntfy#1]
Hi

Awesome Project, but I have some problems with the script:

**Comment by CrazyWolf13** [comment]
@greaterthanlessthan Awesome, got it working. JSON was a bit confusing.

Thanks for sharing this awesome piece!!

But the ntfy action "mark done" seems to be missing the url, can you fix that?

**Comment by CrazyWolf13** [comment]
@greaterthanlessthan 
The reminders also don't seem to work, do they work for you?

**Comment by greaterthanlessthan** [comment]
> @greaterthanlessthan The reminders also don't seem to work, do they work for you?

I only wanted reminders to be notified once, but didn't go to the trouble of having this script clear a reminder once it was triggered. The dumb solution was only notify of a reminder whose time recently occurred, with this line:

`    if True in [datetime.now() > d and (datetime.now() - timedelta(minutes=13) < d) for d in reminders]:
        reminder_tasks.append(t)`

I forget if this is meant to work with a cronjob running every 15 minutes or every 10 minutes, as I don't really use reminders right now, just due dates :)

> But the ntfy action "mark done" seems to be missing the url, can you fix that?

url is assigned in line 72.

**Comment by CrazyWolf13** [comment]
Thanks for the response!

Yeah that's totally fine, but no matter when I define the reminder, I tested with now-20min, now-10min, now+5min, now+10min, now+20 min, I did never get a reminder.

Of thanks, I was confused because of action: http, that seemed like a missing url, you're right!
Altough for me it seems to fail due to CORS errors, did you do anything specifically in that direction?
![image](https://github.com/greaterthanlessthan/vikunja-to-ntfy/assets/96661824/daa10bac-ecc8-4ebc-970b-cfe91cfbaed5)
![image](https://github.com/greaterthanlessthan/vikunja-to-ntfy/assets/96661824/50554f3f-08d6-438a-bd88-c03054aa20d3)
![image](https://github.com/greaterthanlessthan/vikunja-to-ntfy/assets/96661824/f41ce94f-3441-4237-be71-0f2f26f7493e)

**Comment by CrazyWolf13** [comment]
Detailed steps:
Local time is 16:05
I set a reminder to 15:55
I run the full script,
I run the script with -r
I get a message of each overdue task, but none with the message that a task has a reminder.
error endpoint contains NO error and python script runs successfully

**Comment by CrazyWolf13** [comment]
I created a new task with no due date just a reminder that is about 9 minutes ago:

then I added a print statement to each array after line 70:

```
print(overdue_tasks)
print(reminder_tasks)
print(upcoming_tasks)
```
Here the output when running, so it seems like the task is still put to the overdue tasks, even tough it has NO due date set at all.
```
[{'id': 12, 'title': 'testing', 'description': '<p></p>', 'done': False, 'done_at': '0001-01-01T00:00:00Z', 'due_date': '0001-01-01T00:00:00Z', 'reminders': [{'reminder': '2024-05-01T17:05:00Z', 'relative_period': 0, 'relative_to': ''}], 'project_id': 3, 'repeat_after': 0, 'repeat_mode': 0, 'priority': 0, 'start_date': '0001-01-01T00:00:00Z', 'end_date': '0001-01-01T00:00:00Z', 'assignees': None, 'labels': None, 'hex_color': '', 'percent_done': 0, 'identifier': '#1', 'index': 1, 'related_tasks': {}, 'attachments': None, 'cover_image_attachment_id': 0, 'is_favorite': False, 'created': '2024-05-01T17:07:36Z', 'updated': '2024-05-01T17:07:51Z', 'bucket_id': 3, 'position': 65536, 'kanban_position': 65536, 'created_by': {'id': 1, 'name': '', 'username': 'tobias', 'created': '2024-04-28T18:00:44Z', 'updated': '2024-04-28T18:00:45Z'}}]
[]
[]
```

**Comment by CrazyWolf13** [comment]
Could solve, it was a timezone issue, if there's any other time than UTC it gets really complicated
